appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JjgR9ZaIRiuBSvBPsdYXmzzMxSq2eU1JJHNVr8m6MrWXEqP3bz4q+x8Ts6nDOzCjHsZaxUVqStbX/YbKJEXmpbB7mboR6FoG1umlqJoYPXy2YreLXId64fOPXVeqCicXSgkTv23bjijCSbhHSZtlembfmJUn5ryc2SwYv19WKkjXbsprZs0xIX52RkDWHFsUIIZEQDgh4mlRQp5/7sgpCnAgeXtg5/3nFIJ/KhpDFb9wV5spyhE44GL2/dJeC7t/Foq53/XbzVcL7FWDNLWESstE1K6diomtVKcEtEBt1XnJISIR6fN2pADEqvJKiTKNfNxgXw4NUeRkx5crBpD8sssa+d1eYGpnbDjAMOjYtai4pZduw9NGznTftAI64wHEyNceZXpzXoIzYbORN+T4hQR8eUInpD0yt0C2kXV2Oou+iYAQ9hYVHPkmwWSuHLfCcUbLqKhccMT7wWG84ZqpXEFPYJJJy8QeVIAVDR4UDbfUKeoTnxEBtQmGxMTNA54RcaorpQcdE2om3p++5i6hMur/Al/aS/VklqkpoyBy+BAQs36jZwSFYjU6eB0I0zBM3bI53FR8TDy1yoSQDyM9K3kuRhkHmzEAJCO4mMBmb5j+CadhIiZ4bsJ3KKWPWk8ouJRO2Phm8DkKgJfRYoGmIBqM8uuYa7qyFq8P8lL56Jk=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
